-- Optional schema patch for alumni_influencer
-- Keeps the same database name and project URL.

USE alumni_influencer;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS name VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS role VARCHAR(30) NOT NULL DEFAULT 'alumnus',
    ADD COLUMN IF NOT EXISTS is_verified TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bio TEXT NULL,
    ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS job_title_now VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS profile_image VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS extra_monthly_chance TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS created_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL;

ALTER TABLE bids
    ADD COLUMN IF NOT EXISTS bid_date DATE NULL,
    ADD COLUMN IF NOT EXISTS bid_amount DECIMAL(10,2) NULL,
    ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE api_keys
    ADD COLUMN IF NOT EXISTS key_name VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS api_key VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS last_used_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS created_at DATETIME NULL;

ALTER TABLE api_usage_logs
    ADD COLUMN IF NOT EXISTS api_key_id INT NULL,
    ADD COLUMN IF NOT EXISTS endpoint VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS method VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS client_ip VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS used_at DATETIME NULL;

ALTER TABLE degrees
    ADD COLUMN IF NOT EXISTS degree_name VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS institution_name VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS official_url VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS completion_date DATE NULL;

ALTER TABLE certifications
    ADD COLUMN IF NOT EXISTS certification_name VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS organisation_name VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS course_url VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS completion_date DATE NULL,
    ADD COLUMN IF NOT EXISTS sponsor_offer DECIMAL(10,2) NULL,
    ADD COLUMN IF NOT EXISTS is_sponsored TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE professional_licences
    ADD COLUMN IF NOT EXISTS licence_name VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS awarding_body VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS official_url VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS completion_date DATE NULL,
    ADD COLUMN IF NOT EXISTS sponsor_offer DECIMAL(10,2) NULL,
    ADD COLUMN IF NOT EXISTS is_sponsored TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE short_courses
    ADD COLUMN IF NOT EXISTS course_name VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS provider_name VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS course_url VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS completion_date DATE NULL;

ALTER TABLE employment_history
    ADD COLUMN IF NOT EXISTS company_name VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS job_title VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS start_date DATE NULL,
    ADD COLUMN IF NOT EXISTS end_date DATE NULL,
    ADD COLUMN IF NOT EXISTS is_current TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS description TEXT NULL;

ALTER TABLE featured_winners
    ADD COLUMN IF NOT EXISTS bid_id INT NULL,
    ADD COLUMN IF NOT EXISTS feature_date DATE NULL,
    ADD COLUMN IF NOT EXISTS winning_bid DECIMAL(10,2) NULL;

CREATE TABLE IF NOT EXISTS email_verifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    used_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    INDEX (user_id),
    INDEX (token_hash)
);

CREATE TABLE IF NOT EXISTS password_resets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    used_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    INDEX (user_id),
    INDEX (token_hash)
);
